import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it,vi} from 'vitest';
import {CloudSyncModal} from '../components/CloudSyncModal';
import {SavedVersionsModal} from '../components/SavedVersionsModal';
import {Header} from '../components/Header';

const session={roomCode:'ABC123',projectName:'Design',updatedAt:'now',collaborators:[{id:'me',name:'You',avatarColor:'#fff',active:true}],history:[{id:'h',timestamp:'Now',description:'Session created'}]};
describe('saved versions presentation',()=>{
 it('labels the header destination as Saved Versions without collaboration preview status',()=>{const html=renderToStaticMarkup(<Header projectName="Design" onUpdateProjectName={vi.fn()} renderMode="shaded" onChangeRenderMode={vi.fn()} onOpenExportModal={vi.fn()} onOpenAICopilot={vi.fn()} onOpenCloudSync={vi.fn()} onOpenShortcuts={vi.fn()} onTakeSnapshot={vi.fn()} canUndo={false} canRedo={false} onUndo={vi.fn()} onRedo={vi.fn()} onOpenSettings={vi.fn()}/>);expect(html).toContain('aria-label="Open Saved Versions"');expect(html).toContain('title="Saved Versions"');expect(html).not.toContain('Cloud Sync</span>');expect(html).not.toContain('Preview</span>');});
 it('keeps collaboration in Settings without saved-version controls',()=>{const html=renderToStaticMarkup(<CloudSyncModal embedded isOpen onClose={vi.fn()} cloudSession={session} onUpdateCloudSession={vi.fn()} returnFocusRef={{current:null}}/>);expect(html).toMatch(/ABC123.*Copy Code.*Connected Architects.*Sync History Log/s);expect(html).not.toContain('Saved Versions');expect(html).not.toContain('Save Version');});
 it('shows a separate dialog with Current Version first and immutable versions newest-first',()=>{const snapshots=[{id:'new',name:'Newest',createdAt:'2026-02-02T00:00:00.000Z',project:{} as any},{id:'old',name:'Oldest',createdAt:'2026-01-01T00:00:00.000Z',project:{} as any}];const html=renderToStaticMarkup(<SavedVersionsModal isOpen onClose={vi.fn()} authenticated snapshots={snapshots} loading={false} corruptCount={0} busy={false} error={null} notice={null} currentProjectName="Design" autosaveStatus="Saved now" onCreateSnapshot={vi.fn()} onLoadSnapshot={vi.fn()} onDeleteSnapshot={vi.fn()} returnFocusRef={{current:null}}/>);expect(html).toContain('role="dialog"');expect(html.indexOf('Current Version')).toBeLessThan(html.indexOf('Newest'));expect(html.indexOf('Newest')).toBeLessThan(html.indexOf('Oldest'));expect(html).toContain('Save Version');expect(html).toContain('Load');expect(html).toContain('Delete');expect(html.match(/Delete/g)).toHaveLength(2);});
 it('keeps version errors visible in the standalone popup',()=>{const html=renderToStaticMarkup(<SavedVersionsModal isOpen onClose={vi.fn()} authenticated snapshots={[]} loading={false} corruptCount={0} busy={false} error="Save failed" notice={null} currentProjectName="Design" autosaveStatus="Saving" onCreateSnapshot={vi.fn()} onLoadSnapshot={vi.fn()} onDeleteSnapshot={vi.fn()} returnFocusRef={{current:null}}/>);expect(html).toContain('role="alert"');expect(html).toContain('Save failed');});
 it('disables Save Version and every Load while Current Version is not ready',()=>{const snapshot={id:'one',name:'One',createdAt:'2026-01-01T00:00:00.000Z',project:{} as any};const html=renderToStaticMarkup(<SavedVersionsModal isOpen onClose={vi.fn()} authenticated snapshots={[snapshot]} loading={false} corruptCount={0} busy={false} error={null} notice={null} currentProjectName="Design" autosaveStatus="Loading" workspaceReady={false} canRetryHydration={false} onRetryHydration={vi.fn()} onCreateSnapshot={vi.fn()} onLoadSnapshot={vi.fn()} onDeleteSnapshot={vi.fn()} returnFocusRef={{current:null}}/>);expect(html).toMatch(/disabled=""[^>]*>.*Save Version/s);expect(html).toMatch(/disabled=""[^>]*>Load</);});
});
