import {describe,expect,it} from 'vitest';
import type {SceneObject} from '../types';
import {applyMemberDrivenGroupTransform,canTransformGroup,expandGroupedSelection,groupObjects,transformGroupMembers,ungroupObjects,validateGroups} from '../utils/objectGrouping';

const object=(id:string,x:number,z=0):SceneObject=>({id,name:id,type:'cube',category:'primitives',position:[x,0,z],rotation:[0,0,0],scale:[1,1,1],color:'#fff',materialPreset:'default',metalness:0,roughness:.5,transmission:0,visible:true,locked:false});
describe('persisted object groups',()=>{
  it('creates a stable group record and preserves members when ungrouping',()=>{const objects=[object('a',0),object('b',2)];const groups=groupObjects(objects,[],['a','b'],'group-1','Case');expect(groups[0]).toMatchObject({id:'group-1',name:'Case',memberIds:['a','b'],pivot:[1,0,0]});expect(ungroupObjects(groups,'group-1')).toEqual([]);expect(objects.map(item=>item.id)).toEqual(['a','b']);});
  it('rotates and non-uniformly scales members around the shared pivot',()=>{const objects=[object('a',-1),object('b',1)],groups=groupObjects(objects,[],['a','b'],'g');const changed=applyMemberDrivenGroupTransform(objects,groups,'a',[-2,0,0],[0,90,0],[2,1,1]);expect(changed.groups[0].pivot).toEqual([-1,0,0]);expect(changed.objects[0].position).toEqual([-1,0,2]);expect(changed.objects[1].position).toEqual([-1,0,-2]);});
  it('always evaluates preview frames from the frozen start and cannot drift',()=>{const objects=[object('a',-1),object('b',1)],group=groupObjects(objects,[],['a','b'],'g')[0];const first=transformGroupMembers(objects,group,[0,0,0],[0,90,0],[2,1,1]);const repeated=transformGroupMembers(objects,group,[0,0,0],[0,90,0],[2,1,1]);expect(repeated).toEqual(first);});
  it('rejects dangling, overlapping, and Boolean group members',()=>{const objects=[object('a',0),object('b',1)];expect(validateGroups(objects,[{id:'g',name:'G',memberIds:['a','missing'],pivot:[0,0,0],visible:true,locked:false}])).toMatch(/missing/);expect(validateGroups(objects,[{id:'g',name:'G',memberIds:['a','b'],pivot:[0,0,0],visible:true,locked:false},{id:'h',name:'H',memberIds:['a','b'],pivot:[0,0,0],visible:true,locked:false}])).toMatch(/Nested|overlapping/);});
  it('expands member selection and gates hidden or locked groups',()=>{const objects=[object('a',0),object('b',1)],group=groupObjects(objects,[],['a','b'],'g')[0];expect(expandGroupedSelection([group],'b')).toEqual({ids:['a','b'],primaryId:'a'});expect(canTransformGroup(objects,group)).toBeNull();expect(canTransformGroup([{...objects[0],locked:true},objects[1]],group)).toMatch(/Unlock/);expect(canTransformGroup(objects,{...group,visible:false})).toMatch(/hidden/);});
});
