import React,{useEffect,useRef,useState} from 'react';
import {Clock3,Save,X} from 'lucide-react';
import type {NamedSnapshot} from '../utils/accountApi';
import {focusTrapTarget} from '../utils/modalKeyboard';

interface Props{isOpen:boolean;onClose:()=>void;authenticated:boolean;snapshots:NamedSnapshot[];loading:boolean;corruptCount:number;busy:boolean;error:string|null;notice:string|null;currentProjectName:string;autosaveStatus:string;workspaceReady:boolean;canRetryHydration:boolean;onRetryHydration:()=>Promise<void>;onCreateSnapshot:(name:string)=>Promise<boolean>;onLoadSnapshot:(snapshot:NamedSnapshot)=>Promise<void>;onDeleteSnapshot:(snapshot:NamedSnapshot)=>Promise<void>;returnFocusRef:React.RefObject<HTMLButtonElement|null>}
export const SavedVersionsModal:React.FC<Props>=(props)=>{
 const dialogRef=useRef<HTMLDivElement>(null),closeRef=useRef<HTMLButtonElement>(null),nameRef=useRef<HTMLInputElement>(null);const [naming,setNaming]=useState(false),[name,setName]=useState(''),[nameError,setNameError]=useState<string|null>(null);
 useEffect(()=>{if(!props.isOpen)return;closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();props.onClose();return;}if(event.key!=='Tab'||!dialogRef.current)return;const items:HTMLElement[]=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled])'));const next=focusTrapTarget(items.indexOf(document.activeElement as HTMLElement),items.length,event.shiftKey);if(next!==null){event.preventDefault();items[next]?.focus();}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);props.returnFocusRef.current?.focus();};},[props.isOpen,props.onClose,props.returnFocusRef]);
 useEffect(()=>{if(naming)requestAnimationFrame(()=>nameRef.current?.focus());},[naming]);if(!props.isOpen)return null;
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 animate-fade-in" onMouseDown={e=>e.target===e.currentTarget&&props.onClose()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="saved-versions-title" className="max-h-[85vh] w-full max-w-lg overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl"><header className="flex items-center justify-between border-b border-slate-800 bg-slate-950 p-4"><div><h2 id="saved-versions-title" className="text-sm font-bold">Saved Versions</h2><p className="text-[11px] text-slate-400">Save milestones and return to them anytime</p></div><button ref={closeRef} aria-label="Close saved versions" onClick={props.onClose} className="flex h-11 w-11 items-center justify-center rounded-lg text-slate-400 hover:bg-slate-800 hover:text-white"><X className="h-5 w-5"/></button></header><div className="max-h-[68vh] space-y-3 overflow-y-auto p-5">
 {(props.error||props.notice)&&<div className="space-y-2"><p role={props.error?'alert':'status'} className={`rounded-lg border px-3 py-2 text-xs ${props.error?'border-red-500/40 bg-red-500/10 text-red-200':'border-emerald-500/40 bg-emerald-500/10 text-emerald-200'}`}>{props.error||props.notice}</p>{props.canRetryHydration&&<button disabled={props.busy} onClick={()=>void props.onRetryHydration()} className="rounded-lg border border-red-400/40 px-3 py-2 text-xs font-semibold text-red-100 disabled:opacity-40">Retry Current Version</button>}</div>}
 <div className="flex items-center justify-between rounded-xl border border-sky-500/30 bg-sky-500/10 p-3"><span><strong className="block text-sm text-sky-100">Current Version</strong><span className="text-[11px] text-sky-300">{props.authenticated?props.autosaveStatus:'Sign in in Settings to sync this version.'}</span></span><Clock3 className="h-4 w-4 text-sky-400"/></div>
 {props.authenticated&&<>{!naming?<button disabled={props.busy||!props.workspaceReady} onClick={()=>{setName(props.currentProjectName);setNameError(null);setNaming(true);}} className="flex w-full items-center justify-center gap-2 rounded-lg bg-sky-600 px-3 py-2 text-xs font-semibold disabled:opacity-40"><Save className="h-4 w-4"/>Save Version</button>:<form aria-label="Name saved version" onSubmit={async e=>{e.preventDefault();if(!props.workspaceReady)return;const value=name.trim();if(value.length<1||value.length>80){setNameError('Version name must be 1-80 characters.');return;}if(await props.onCreateSnapshot(value)){setNaming(false);setName('');}}} className="space-y-2 rounded-xl border border-slate-800 bg-slate-950/60 p-3"><input ref={nameRef} aria-label="Version name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"/>{nameError&&<p role="alert" className="text-xs text-red-300">{nameError}</p>}<div className="flex gap-3"><button disabled={props.busy||!props.workspaceReady} className="text-xs font-semibold text-sky-300">Save</button><button type="button" onClick={()=>setNaming(false)} className="text-xs text-slate-400">Cancel</button></div></form>}</>}
 {!props.authenticated?null:props.loading?<p role="status" className="text-xs text-slate-500">Loading saved versions…</p>:props.snapshots.length===0?<p className="text-xs text-slate-500">No saved versions yet.</p>:<div className="space-y-2">{props.snapshots.map(s=><div key={s.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/60 p-3 text-xs"><span className="min-w-0"><strong className="block truncate text-slate-200">{s.name}</strong><time dateTime={s.createdAt} className="font-mono text-[10px] text-slate-500">{new Date(s.createdAt).toLocaleString()}</time></span><span className="flex gap-2"><button disabled={props.busy||!props.workspaceReady} onClick={()=>void props.onLoadSnapshot(s)} className="text-sky-300 disabled:opacity-40">Load</button><button disabled={props.busy} onClick={()=>void props.onDeleteSnapshot(s)} className="text-red-300 disabled:opacity-40">Delete</button></span></div>)}</div>}{props.authenticated&&props.corruptCount>0&&<p role="alert" className="text-xs text-amber-300">{props.corruptCount} corrupt saved version{props.corruptCount===1?' was':'s were'} skipped.</p>}
 </div></div></div>;
};
