import React,{useEffect,useRef,useState} from 'react';
import {Clock3,Save,X} from 'lucide-react';
import type {NamedSnapshot} from '../utils/accountApi';
import {focusTrapTarget} from '../utils/modalKeyboard';
import {validateVersionName} from '../utils/savedVersionForm';

interface Props{isOpen:boolean;onClose:()=>void;authenticated:boolean;snapshots:NamedSnapshot[];loading:boolean;corruptCount:number;busy:boolean;error:string|null;notice:string|null;currentProjectName:string;autosaveStatus:string;workspaceReady:boolean;canRetryHydration:boolean;onRetryHydration:()=>Promise<void>;onCreateSnapshot:(name:string)=>Promise<boolean>;onRenameSnapshot:(snapshot:NamedSnapshot,name:string)=>Promise<boolean>;onLoadSnapshot:(snapshot:NamedSnapshot)=>Promise<void>;onDeleteSnapshot:(snapshot:NamedSnapshot)=>Promise<void>;returnFocusRef:React.RefObject<HTMLButtonElement|null>}
const validName=validateVersionName;
export const SavedVersionsModal:React.FC<Props>=(props)=>{
 const dialogRef=useRef<HTMLDivElement>(null),closeRef=useRef<HTMLButtonElement>(null),saveTriggerRef=useRef<HTMLButtonElement>(null),renameTriggerRef=useRef<HTMLButtonElement|null>(null),submitting=useRef(false);
 const [mode,setMode]=useState<{kind:'save'}|{kind:'rename';snapshot:NamedSnapshot}|null>(null),[saveName,setSaveName]=useState(''),[saveError,setSaveError]=useState<string|null>(null),[renameName,setRenameName]=useState(''),[renameError,setRenameError]=useState<string|null>(null);
 const cancelMode=()=>{if(props.busy||submitting.current)return;const previous=mode;setMode(null);setSaveError(null);setRenameError(null);requestAnimationFrame(()=>previous?.kind==='save'?saveTriggerRef.current?.focus():renameTriggerRef.current?.focus());};
 const close=()=>{if(!props.busy&&!submitting.current)props.onClose();};
 useEffect(()=>{if(!props.isOpen)return;closeRef.current?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();if(mode)cancelMode();else close();return;}if(event.key!=='Tab'||!dialogRef.current)return;const items=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled])')) as HTMLElement[];const next=focusTrapTarget(items.indexOf(document.activeElement as HTMLElement),items.length,event.shiftKey);if(next!==null){event.preventDefault();items[next]?.focus();}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);props.returnFocusRef.current?.focus();};},[props.isOpen,props.busy,mode]);
 if(!props.isOpen)return null;
 const startSave=()=>{setMode({kind:'save'});setSaveName(props.currentProjectName);setSaveError(null);setRenameError(null);};
 const startRename=(snapshot:NamedSnapshot,button:HTMLButtonElement)=>{renameTriggerRef.current=button;setMode({kind:'rename',snapshot});setRenameName(snapshot.name);setRenameError(null);setSaveError(null);};
 const submitSave=async(event:React.FormEvent)=>{event.preventDefault();if(props.busy||submitting.current||!props.workspaceReady)return;const result=validName(saveName);setSaveError(result.error);if(result.error)return;submitting.current=true;try{if(await props.onCreateSnapshot(result.name)){setMode(null);requestAnimationFrame(()=>saveTriggerRef.current?.focus());}}finally{submitting.current=false;}};
 const submitRename=async(event:React.FormEvent,snapshot:NamedSnapshot)=>{event.preventDefault();if(props.busy||submitting.current)return;const result=validName(renameName);setRenameError(result.error);if(result.error)return;submitting.current=true;try{if(await props.onRenameSnapshot(snapshot,result.name)){setMode(null);requestAnimationFrame(()=>renameTriggerRef.current?.focus());}}finally{submitting.current=false;}};
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 backdrop-blur-md p-4 animate-fade-in" onMouseDown={event=>event.target===event.currentTarget&&close()}><div ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="saved-versions-title" className="max-h-[85vh] w-full max-w-lg overflow-hidden rounded-2xl border border-slate-800 bg-slate-900 shadow-2xl"><header className="flex items-center justify-between border-b border-slate-800 bg-slate-950 p-4"><div><h2 id="saved-versions-title" className="text-sm font-bold">Saved Versions</h2><p className="text-[11px] text-slate-400">Save milestones and return to them anytime</p></div><button ref={closeRef} disabled={props.busy} aria-label="Close saved versions" onClick={close} className="flex h-11 w-11 items-center justify-center rounded-lg text-slate-400 disabled:opacity-40"><X className="h-5 w-5"/></button></header><div className="max-h-[68vh] space-y-3 overflow-y-auto p-5">
 {(props.error||props.notice)&&<p role={props.error?'alert':'status'} className="rounded-lg border px-3 py-2 text-xs">{props.error||props.notice}</p>}
 <div className="flex items-center justify-between rounded-xl border border-sky-500/30 bg-sky-500/10 p-3"><span><strong className="block text-sm text-sky-100">Current Version</strong><span className="text-[11px] text-sky-300">{props.authenticated?props.autosaveStatus:'Sign in in Settings to sync this version.'}</span></span><Clock3 className="h-4 w-4 text-sky-400"/></div>
 {props.canRetryHydration&&<button disabled={props.busy} onClick={()=>void props.onRetryHydration()} className="text-xs text-red-200">Retry Current Version</button>}
 {props.authenticated&&mode?.kind!=='save'&&<button ref={saveTriggerRef} disabled={props.busy||!props.workspaceReady} onClick={startSave} className="flex w-full items-center justify-center gap-2 rounded-lg bg-sky-600 px-3 py-2 text-xs font-semibold disabled:opacity-40"><Save className="h-4 w-4"/>Save Version</button>}
 {mode?.kind==='save'&&<form aria-label="Name saved version" onSubmit={submitSave} className="space-y-2 rounded-xl border border-slate-800 bg-slate-950/60 p-3"><input autoFocus disabled={props.busy} aria-label="Version name" maxLength={80} value={saveName} onChange={e=>setSaveName(e.target.value)} className="w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-xs"/>{saveError&&<p role="alert" className="text-xs text-red-300">{saveError}</p>}<div className="flex gap-3"><button disabled={props.busy||!props.workspaceReady} className="text-xs font-semibold text-sky-300">Save</button><button disabled={props.busy} type="button" onClick={cancelMode} className="text-xs text-slate-400">Cancel</button></div></form>}
 {!props.authenticated?null:props.loading?<p role="status" className="text-xs text-slate-500">Loading saved versions…</p>:props.snapshots.length===0?<p className="text-xs text-slate-500">No saved versions yet.</p>:<div className="space-y-2">{props.snapshots.map(snapshot=><div key={snapshot.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 bg-slate-950/60 p-3 text-xs"><span className="min-w-0 flex-1">{mode?.kind==='rename'&&mode.snapshot.id===snapshot.id?<form aria-label={`Rename ${snapshot.name}`} onSubmit={event=>void submitRename(event,snapshot)}><input autoFocus disabled={props.busy} aria-label="New version name" maxLength={80} value={renameName} onChange={e=>setRenameName(e.target.value)} className="w-full rounded border border-slate-700 bg-slate-950 px-2 py-1"/>{renameError&&<span role="alert" className="block text-red-300">{renameError}</span>}<span className="mt-1 flex gap-2"><button disabled={props.busy} className="text-sky-300">Save Name</button><button disabled={props.busy} type="button" onClick={cancelMode} className="text-slate-400">Cancel</button></span></form>:<><strong className="block truncate text-slate-200">{snapshot.name}</strong><time dateTime={snapshot.createdAt} className="font-mono text-[10px] text-slate-500">{new Date(snapshot.createdAt).toLocaleString()}</time></>}</span>{!(mode?.kind==='rename'&&mode.snapshot.id===snapshot.id)&&<span className="flex gap-2"><button disabled={props.busy} onClick={event=>startRename(snapshot,event.currentTarget)} className="text-violet-300">Rename</button><button disabled={props.busy||!props.workspaceReady} onClick={()=>void props.onLoadSnapshot(snapshot)} className="text-sky-300">Load</button><button disabled={props.busy} onClick={()=>void props.onDeleteSnapshot(snapshot)} className="text-red-300">Delete</button></span>}</div>)}</div>}
 {props.authenticated&&props.corruptCount>0&&<p role="alert" className="text-xs text-amber-300">{props.corruptCount} corrupt saved version{props.corruptCount===1?' was':'s were'} skipped.</p>}
 </div></div></div>;
};
