import * as THREE from 'three';
export interface FrozenPlanarFace{centroid:[number,number,number];normal:[number,number,number];basisU:[number,number,number];basisV:[number,number,number];profile:[number,number][];attachmentLoop:[number,number,number][];signature:string;sourceFingerprint:string;triangleIndices:number[];boundaryNeighborDotMax:number;meshPath?:number[]}
export const FACE_TRIANGLE_LIMIT=75_000;
export function geometryFingerprint(geometry:THREE.BufferGeometry):string{let hash=2166136261;const mix=(value:number)=>{const text=Number.isFinite(value)?value.toPrecision(12):String(value);for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}hash^=124;hash=Math.imul(hash,16777619);};const position=geometry.getAttribute('position'),normal=geometry.getAttribute('normal');for(let i=0;i<(position?.count??0);i++){mix(position.getX(i));mix(position.getY(i));mix(position.getZ(i));}if(geometry.index)for(let i=0;i<geometry.index.count;i++)mix(geometry.index.getX(i));if(normal)for(let i=0;i<normal.count;i++){mix(normal.getX(i));mix(normal.getY(i));mix(normal.getZ(i));}return `${position?.count??0}:${geometry.index?.count??0}:${hash>>>0}`;}
export function faceExtrusionEligibility(_type:string,geometry:THREE.BufferGeometry,faceIndex:number):{face:FrozenPlanarFace;error:null}|{face:null;error:string}{try{return {face:extractPlanarFace(geometry,faceIndex),error:null};}catch(error){return {face:null,error:error instanceof Error?error.message:'The selected mesh face is not eligible.'};}}
type Edge={a:number;b:number;triangles:{triangle:number;forward:boolean}[]};
export function extractPlanarFace(geometry:THREE.BufferGeometry,faceIndex:number,requireSupportingPlane=true):FrozenPlanarFace{
 const attr=geometry.getAttribute('position');if(!attr)throw new Error('Geometry has no positions.');const rawCount=geometry.index?.count??attr.count;if(rawCount%3!==0)throw new Error('Geometry has invalid triangle data.');const triangleCount=rawCount/3;if(triangleCount>FACE_TRIANGLE_LIMIT)throw new Error('Geometry exceeds the interactive triangle limit.');if(!Number.isInteger(faceIndex)||faceIndex<0||faceIndex>=triangleCount)throw new Error('Selected face is missing.');
 if(geometry.index){for(let i=0;i<geometry.index.count;i++){const value=geometry.index.getX(i);if(!Number.isInteger(value)||value<0||value>=attr.count)throw new Error('Geometry index contains a non-integer or out-of-range vertex.');}}
 const raw:THREE.Vector3[]=[];for(let i=0;i<attr.count;i++){const v=new THREE.Vector3().fromBufferAttribute(attr,i);if(![v.x,v.y,v.z].every(Number.isFinite))throw new Error('Geometry contains non-finite positions.');raw.push(v);}const bounds=new THREE.Box3().setFromPoints(raw),scale=Math.max(bounds.getSize(new THREE.Vector3()).length(),1e-9),weldTolerance=Math.max(1e-12,scale*1e-7),planeTolerance=Math.max(1e-12,scale*1e-6),areaTolerance=Math.max(1e-24,scale*scale*1e-12),collinearTolerance=Math.max(1e-24,scale*scale*1e-8);
 const welded:THREE.Vector3[]=[],weldMap=new Map<string,number>();const weld=(v:THREE.Vector3)=>{const k=`${Math.round(v.x/weldTolerance)},${Math.round(v.y/weldTolerance)},${Math.round(v.z/weldTolerance)}`;let id=weldMap.get(k);if(id===undefined){id=welded.length;weldMap.set(k,id);welded.push(v.clone());}return id;};const index=geometry.index;const ids:number[][]=[];for(let t=0;t<triangleCount;t++)ids.push([0,1,2].map(c=>weld(raw[index?index.getX(t*3+c):t*3+c])));
 const normals:THREE.Vector3[]=[],planes:number[]=[],triangleEdges:string[][]=[],edges=new Map<string,Edge>();for(let t=0;t<triangleCount;t++){const [ia,ib,ic]=ids[t],a=welded[ia],b=welded[ib],c=welded[ic],n=new THREE.Vector3().crossVectors(new THREE.Vector3().subVectors(b,a),new THREE.Vector3().subVectors(c,a));if(ia===ib||ib===ic||ic===ia||n.lengthSq()<=areaTolerance*areaTolerance)throw new Error('Geometry contains a degenerate triangle.');n.normalize();normals.push(n);planes.push(n.dot(a));const keys:string[]=[];for(const [x,y] of [[ia,ib],[ib,ic],[ic,ia]]){const forward=x<y,k=forward?`${x}|${y}`:`${y}|${x}`,edge=edges.get(k)??{a:Math.min(x,y),b:Math.max(x,y),triangles:[]};edge.triangles.push({triangle:t,forward});edges.set(k,edge);keys.push(k);}triangleEdges.push(keys);}
 for(const edge of edges.values()){if(edge.triangles.length!==2)throw new Error('Geometry is open or nonmanifold.');if(edge.triangles[0].forward===edge.triangles[1].forward)throw new Error('Geometry has inconsistent face winding.');}
 let signedVolume=0;for(const [a,b,c] of ids)signedVolume+=welded[a].dot(new THREE.Vector3().crossVectors(welded[b],welded[c]))/6;if(!Number.isFinite(signedVolume)||signedVolume<=scale*scale*scale*1e-12)throw new Error('Geometry must be a closed solid with outward face winding and positive volume.');
 const connected=new Set([0]),connectQueue=[0];while(connectQueue.length){const t=connectQueue.pop()!;for(const k of triangleEdges[t])for(const item of edges.get(k)!.triangles)if(!connected.has(item.triangle)){connected.add(item.triangle);connectQueue.push(item.triangle);}}if(connected.size!==triangleCount)throw new Error('Geometry contains disconnected solids.');
 const baseN=normals[faceIndex],baseD=planes[faceIndex],region=new Set([faceIndex]),queue=[faceIndex];while(queue.length){const t=queue.pop()!;for(const k of triangleEdges[t])for(const item of edges.get(k)!.triangles){const other=item.triangle;if(!region.has(other)&&normals[other].dot(baseN)>=1-1e-6&&Math.abs(planes[other]-baseD)<=planeTolerance){region.add(other);queue.push(other);}}}
 if(requireSupportingPlane)for(let id=0;id<welded.length;id++)if(welded[id].dot(baseN)-baseD>planeTolerance)throw new Error('Selected face is recessed and is not on a supporting plane of the solid.');
 const boundary:[number,number][]= [];let boundaryNeighborDotMax=-1;for(const t of region){for(let i=0;i<3;i++){const k=triangleEdges[t][i],edge=edges.get(k)!,outside=edge.triangles.find(item=>!region.has(item.triangle));if(outside){boundary.push([ids[t][i],ids[t][(i+1)%3]]);boundaryNeighborDotMax=Math.max(boundaryNeighborDotMax,normals[outside.triangle].dot(baseN));}}}if(boundary.length<3)throw new Error('Planar face boundary must contain at least 3 vertices.');const next=new Map<number,number[]>(),incoming=new Map<number,number>();for(const [a,b] of boundary){next.set(a,[...(next.get(a)??[]),b]);incoming.set(b,(incoming.get(b)??0)+1);}if([...next.values()].some(v=>v.length!==1)||[...incoming.values()].some(n=>n!==1)||next.size!==boundary.length)throw new Error('Planar face has holes, multiple loops, or a self-intersecting boundary.');
 let start=Math.min(...next.keys()),current=start;const loop:number[]=[];do{if(loop.includes(current))throw new Error('Planar face boundary self-intersects.');loop.push(current);current=next.get(current)?.[0]??-1;}while(current!==start&&current>=0);if(current!==start||loop.length!==boundary.length)throw new Error('Planar face boundary contains multiple loops.');
 const attachmentPoints=loop.map(id=>welded[id]);if(attachmentPoints.length>512)throw new Error('Planar face attachment boundary exceeds 512 vertices.');let points=attachmentPoints.slice();let changed=true;while(changed&&points.length>3){changed=false;for(let i=0;i<points.length;i++){const previous=points[(i-1+points.length)%points.length],currentPoint=points[i],following=points[(i+1)%points.length],a=new THREE.Vector3().subVectors(currentPoint,previous),b=new THREE.Vector3().subVectors(following,currentPoint);if(new THREE.Vector3().crossVectors(a,b).length()<=collinearTolerance&&a.dot(b)>=0){points.splice(i,1);changed=true;break;}}}if(points.length<3||points.length>64)throw new Error('Planar face boundary must contain 3-64 non-collinear vertices.');const origin=points[0].clone(),u=new THREE.Vector3().subVectors(points[1],points[0]).normalize(),v=new THREE.Vector3().crossVectors(baseN,u).normalize();let projected=points.map(p=>{const d=p.clone().sub(origin);return [d.dot(u),d.dot(v)] as [number,number];}),crossSum=0,cx=0,cy=0;for(let i=0;i<projected.length;i++){const p=projected[i],q=projected[(i+1)%projected.length],cross=p[0]*q[1]-q[0]*p[1];crossSum+=cross;cx+=(p[0]+q[0])*cross;cy+=(p[1]+q[1])*cross;}if(Math.abs(crossSum)<=areaTolerance)throw new Error('Planar face has negligible projected area.');cx/=3*crossSum;cy/=3*crossSum;const centroid=origin.clone().addScaledVector(u,cx).addScaledVector(v,cy);let profile=projected.map(([x,y])=>[x-cx,y-cy] as [number,number]);if(crossSum<0)profile=profile.slice().reverse();
 const coords=points.map(p=>p.toArray().map(n=>Math.round(n/weldTolerance))),rotations=coords.map((_,i)=>coords.slice(i).concat(coords.slice(0,i))),canonical3d=rotations.map(value=>JSON.stringify(value)).sort()[0],normalKey=baseN.toArray().map(n=>Math.round(n*1e9)),planeKey=Math.round(baseD/weldTolerance),triangleIndices=[...region].sort((a,b)=>a-b);return {centroid:centroid.toArray() as [number,number,number],normal:baseN.toArray() as [number,number,number],basisU:u.toArray() as [number,number,number],basisV:v.toArray() as [number,number,number],profile,attachmentLoop:attachmentPoints.map(p=>p.toArray() as [number,number,number]),signature:JSON.stringify([canonical3d,normalKey,planeKey]),sourceFingerprint:geometryFingerprint(geometry),triangleIndices,boundaryNeighborDotMax};
}
