import * as THREE from 'three';

export interface FrozenPlanarFace {centroid:[number,number,number];normal:[number,number,number];basisU:[number,number,number];basisV:[number,number,number];profile:[number,number][];signature:string;triangleIndices:number[]}
export const FACE_TRIANGLE_LIMIT=75_000;
const key=(v:THREE.Vector3)=>`${Math.round(v.x*1e6)},${Math.round(v.y*1e6)},${Math.round(v.z*1e6)}`;
export function extractPlanarFace(geometry:THREE.BufferGeometry,faceIndex:number):FrozenPlanarFace{
 const source=geometry.index?geometry.toNonIndexed():geometry.clone(),position=source.getAttribute('position');
 try{if(!position||position.count%3!==0)throw new Error('Geometry has invalid triangle data.');const triangleCount=position.count/3;if(triangleCount>FACE_TRIANGLE_LIMIT)throw new Error('Geometry exceeds the interactive triangle limit.');if(!Number.isInteger(faceIndex)||faceIndex<0||faceIndex>=triangleCount)throw new Error('Selected face is missing.');
  const vertices:THREE.Vector3[]=[];for(let i=0;i<position.count;i++)vertices.push(new THREE.Vector3().fromBufferAttribute(position,i));
  const normals:THREE.Vector3[]=[],planes:number[]=[];for(let i=0;i<triangleCount;i++){const a=vertices[i*3],b=vertices[i*3+1],c=vertices[i*3+2],normal=new THREE.Vector3().crossVectors(new THREE.Vector3().subVectors(b,a),new THREE.Vector3().subVectors(c,a));if(normal.lengthSq()<1e-16)throw new Error('Geometry contains a degenerate triangle.');normal.normalize();normals.push(normal);planes.push(normal.dot(a));}
  const edgeTriangles=new Map<string,number[]>(),directed=new Map<string,[string,string]>();for(let t=0;t<triangleCount;t++)for(const [a,b] of [[0,1],[1,2],[2,0]]){const ka=key(vertices[t*3+a]),kb=key(vertices[t*3+b]),ek=ka<kb?`${ka}|${kb}`:`${kb}|${ka}`,list=edgeTriangles.get(ek)??[];list.push(t);edgeTriangles.set(ek,list);directed.set(`${t}:${ek}`,[ka,kb]);}if([...edgeTriangles.values()].some(list=>list.length>2))throw new Error('Geometry is nonmanifold.');
  const baseN=normals[faceIndex],baseD=planes[faceIndex],region=new Set([faceIndex]),queue=[faceIndex];while(queue.length){const t=queue.pop()!;for(const [ek,list] of edgeTriangles){if(!list.includes(t))continue;for(const other of list)if(!region.has(other)&&normals[other].dot(baseN)>1-1e-5&&Math.abs(planes[other]-baseD)<1e-5){region.add(other);queue.push(other);}}}if(region.size<2)throw new Error('The selected triangle is not part of a stable planar region.');
  if(triangleCount>24&&region.size===2)throw new Error('The selected surface is curved rather than planar.');
  const boundary:[string,string][]=[];for(const t of region)for(const [ek,list] of edgeTriangles)if(list.includes(t)&&list.filter(x=>region.has(x)).length===1)boundary.push(directed.get(`${t}:${ek}`)!);if(boundary.length<3||boundary.length>64)throw new Error('Planar face boundary must contain 3-64 vertices.');
  const next=new Map<string,string[]>();for(const [a,b] of boundary){const list=next.get(a)??[];list.push(b);next.set(a,list);}if([...next.values()].some(list=>list.length!==1)||next.size!==boundary.length)throw new Error('Planar face has holes, multiple loops, or a self-intersecting boundary.');
  const ordered:string[]=[],start=boundary[0][0];let current=start;do{if(ordered.includes(current))throw new Error('Planar face boundary self-intersects.');ordered.push(current);current=next.get(current)?.[0]??'';}while(current&&current!==start);if(current!==start||ordered.length!==boundary.length)throw new Error('Planar face boundary contains multiple loops.');
  const lookup=new Map(vertices.map(v=>[key(v),v]));const points=ordered.map(k=>lookup.get(k)!.clone()),centroid=points.reduce((s,p)=>s.add(p),new THREE.Vector3()).divideScalar(points.length);const u=new THREE.Vector3().subVectors(points[1],points[0]).normalize(),v=new THREE.Vector3().crossVectors(baseN,u).normalize();const profile=points.map(p=>{const d=p.clone().sub(centroid);return [d.dot(u),d.dot(v)] as [number,number];});
  const signature=JSON.stringify([ordered.map(k=>k),baseN.toArray().map(n=>+n.toFixed(6))]);return {centroid:centroid.toArray() as [number,number,number],normal:baseN.toArray() as [number,number,number],basisU:u.toArray() as [number,number,number],basisV:v.toArray() as [number,number,number],profile,signature,triangleIndices:[...region].sort((a,b)=>a-b)};
 }finally{source.dispose();}
}
